links:
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1543267
  results:
  - test: position-absolute-001.html
  - test: position-absolute-002.html
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1500492
  results:
  - test: flex-minimum-width-flex-items-004.xht
  - test: flex-minimum-width-flex-items-006.xht
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=209871
  results:
  - test: align-content-wrap-001.html
    status: FAIL
  - test: align-content-wrap-002.html
    status: FAIL
  - test: align-content-wrap-003.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=210077
  results:
  - test: flex-aspect-ratio-img-column-010.html
    status: FAIL
  - test: flex-basis-010.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=172026
  results:
  - test: flex-item-contains-strict.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=210088
  results:
  - test: flex-minimum-height-flex-items-010.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=210089
  results:
  - test: flex-minimum-height-flex-items-011.xht
    status: FAIL
  - test: flex-minimum-height-flex-items-013.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=185771
  results:
  - test: hittest-overlapping-margin.html
    status: FAIL
  - test: hittest-overlapping-order.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=210103
  results:
  - test: item-with-table-with-infinite-max-intrinsic-width.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=210091
  results:
  - test: radiobutton-min-size.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=210093
  results:
  - test: select-element-zero-height-001.html
    status: FAIL
  - test: select-element-zero-height-002.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=210102
  results:
  - test: table-as-item-auto-min-width.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=209871
  results:
  - test: align-content-wrap-001.html
    status: FAIL
  - test: align-content-wrap-002.html
    status: FAIL
  - test: align-content-wrap-003.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=210077
  results:
  - test: flex-aspect-ratio-img-column-010.html
    status: FAIL
  - test: flex-basis-010.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=172026
  results:
  - test: flex-item-contains-strict.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=210088
  results:
  - test: flex-minimum-height-flex-items-010.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=210089
  results:
  - test: flex-minimum-height-flex-items-011.xht
    status: FAIL
  - test: flex-minimum-height-flex-items-013.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=185771
  results:
  - test: hittest-overlapping-margin.html
    status: FAIL
  - test: hittest-overlapping-order.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=210103
  results:
  - test: item-with-table-with-infinite-max-intrinsic-width.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=210091
  results:
  - test: radiobutton-min-size.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=210093
  results:
  - test: select-element-zero-height-001.html
    status: FAIL
  - test: select-element-zero-height-002.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=210102
  results:
  - test: table-as-item-auto-min-width.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=210144
  results:
  - test: anonymous-flex-item-004.html
    status: FAIL
  - test: anonymous-flex-item-005.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=210465
  results:
  - test: flex-wrap-002.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=209871
  results:
  - test: flex-wrap-005.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=145176
  results:
  - test: flexbox_align-items-stretch-3.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=210474
  results:
  - test: flexbox_first-letter.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=136754
  results:
  - test: flexbox_stf-table-singleline-2.html
    status: FAIL
  - test: flexbox_stf-table-singleline.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=210475
  results:
  - test: image-items-flake-001.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=210477
  results:
  - test: percentage-heights-003.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=210478
  results:
  - test: percentage-heights-006.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=210243
  results:
  - test: percentage-size-quirks.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=210144
  results:
  - test: anonymous-flex-item-004.html
    status: FAIL
  - test: anonymous-flex-item-005.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=210465
  results:
  - test: flex-wrap-002.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=209871
  results:
  - test: flex-wrap-005.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=145176
  results:
  - test: flexbox_align-items-stretch-3.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=210474
  results:
  - test: flexbox_first-letter.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=136754
  results:
  - test: flexbox_stf-table-singleline-2.html
    status: FAIL
  - test: flexbox_stf-table-singleline.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=210475
  results:
  - test: image-items-flake-001.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=210477
  results:
  - test: percentage-heights-003.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=210478
  results:
  - test: percentage-heights-006.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=210243
  results:
  - test: percentage-size-quirks.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=210791
  results:
  - test: quirks-auto-block-size-with-percentage-item.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=210791
  results:
  - test: quirks-auto-block-size-with-percentage-item.html
    status: FAIL
