links:
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=207678
  results:
  - test: a-element-origin-xhtml.xhtml
    status: FAIL
  - test: a-element-origin.html
    status: FAIL
  - test: a-element-xhtml.xhtml
    status: FAIL
  - test: a-element.html
    status: FAIL
