links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=119175
  results:
  - test: "*"
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=119175
  results:
  - test: "*"
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=180645
  results:
  - test: type-change-state.html
    status: FAIL
