links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=195275
  results:
  - test: tab-min-rendered-width-1.html
    status: FAIL
  - test: tab-size-spacing-001.html
    status: FAIL
