links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=182922
  results:
  - test: grid-auto-repeat-multiple-values-001.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=182922
  results:
  - test: grid-auto-repeat-multiple-values-001.html
    status: FAIL
