links:
- product: firefox
  results:
  - subtest: Caption with margin
    test: table-offset-props.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1474448
- product: firefox
  results:
  - subtest: Sticky elements work with the root (document) scroller
    test: position-sticky-root-scroller-with-scroll-behavior.html
  - subtest: BODY element scroll-behavior should not propagate to viewport
    test: scroll-behavior-smooth.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1556685
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=182292
  results:
  - test: scrollingElement-quirks-dynamic-001.html
    status: FAIL
  - test: scrollingElement-quirks-dynamic-002.html
    status: FAIL
