links:
- product: firefox
  results:
  - test: selector-read-write-type-change-002.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=312971
- product: firefox
  results:
  - test: floating-first-letter-05d0.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1495674
- product: firefox
  results:
  - test: selector-placeholder-shown-type-change-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1401657
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=64861
  results:
  - test: selectors-dir-selector-ltr-001.html
    status: FAIL
  - test: selectors-dir-selector-rtl-001.html
    status: FAIL
