links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=203416
  results:
  - test: before-load-001.html
    status: TIMEOUT
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=203416
  results:
  - test: properties-value-auto-001.html
    status: FAIL
