links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=191367
  results:
  - test: grid-container-ignores-first-letter-002.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=191367
  results:
  - test: grid-container-ignores-first-letter-002.html
    status: FAIL
