links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=206882
  results:
  - test: at-font-face-font-matching.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=206882
  results:
  - test: at-font-face-font-matching.html
    status: FAIL
