links:
- product: safari
  url: https://github.com/web-platform-tests/wpt/issues/21854
  results:
  - test: "*"
- product: webkitgtk
  url: https://github.com/web-platform-tests/wpt/issues/21854
  results:
  - test: "*"
