links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=161472
  results:
  - test: workers.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=161472
  results:
  - test: workers.html
    status: FAIL
