links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=195275
  results:
  - test: letter-spacing-bidi-001.html
    status: FAIL
  - test: letter-spacing-bidi-002.html
    status: FAIL
  - test: letter-spacing-end-of-line-001.html
    status: FAIL
  - test: letter-spacing-nesting-001.html
    status: FAIL
  - test: letter-spacing-nesting-002.html
    status: FAIL
