links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=204611
  results:
  - test: grid-area-shorthand.html
    status: FAIL
  - test: grid-shorthand.html
    status: FAIL
  - test: grid-template-shorthand.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=204611
  results:
  - test: grid-area-shorthand.html
    status: FAIL
  - test: grid-shorthand.html
    status: FAIL
  - test: grid-template-shorthand.html
    status: FAIL
