links:
- product: firefox
  results:
  - test: fetch-request-css-base-url.https.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1201160
- product: firefox
  results:
  - test: fetch-request-css-images.https.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1532331
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=182176
  results:
  - test: appcache-ordering-main.https.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=201665
  results:
  - test: fetch-canvas-tainting-video.https.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=201666
  results:
  - test: fetch-canvas-tainting-video-with-range-request.https.html
    status: FAIL
