links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=15257
  results:
  - test: font-size-adjust-interpolation.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=15257
  results:
  - test: font-size-adjust-interpolation.html
    status: FAIL
