links:
- product: chrome
  url: crbug.com/571722
  results:
  - test: setrequestheader-header-allowed.htm
    subtest: "XMLHttpRequest: setRequestHeader() - headers that are allowed (User-Agent)"
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=209801
  results:
  - test: header-user-agent-sync.htm
    status: FAIL
