links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=175287
  results:
  - test: box-sizing-014.html
    status: FAIL
  - test: box-sizing-015.html
    status: FAIL
  - test: box-sizing-016.html
    status: FAIL
  - test: box-sizing-018.html
    status: FAIL
  - test: box-sizing-019.html
    status: FAIL
  - test: box-sizing-024.html
    status: FAIL
  - test: box-sizing-025.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=175288
  results:
  - test: outline-005.html
    status: FAIL
  - test: outline-013.html
    status: FAIL
  - test: outline-014.html
    status: FAIL
  - test: outline-015.html
    status: FAIL
  - test: outline-016.html
    status: FAIL
  - test: outline-019.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=175287
  results:
  - test: box-sizing-014.html
    status: FAIL
  - test: box-sizing-015.html
    status: FAIL
  - test: box-sizing-016.html
    status: FAIL
  - test: box-sizing-018.html
    status: FAIL
  - test: box-sizing-019.html
    status: FAIL
  - test: box-sizing-024.html
    status: FAIL
  - test: box-sizing-025.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=175288
  results:
  - test: outline-005.html
    status: FAIL
  - test: outline-013.html
    status: FAIL
  - test: outline-014.html
    status: FAIL
  - test: outline-015.html
    status: FAIL
  - test: outline-016.html
    status: FAIL
  - test: outline-019.html
    status: FAIL
