links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=148816
  results:
  - test: multicol-rule-004.xht
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=153698
  results:
  - test: multicol-rule-dashed-000.xht
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=148816
  results:
  - test: multicol-rule-004.xht
    status: FAIL
