links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=203530
  results:
  - test: text-decoration-line-recalc.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=203531
  results:
  - test: text-decoration-propagation-shadow.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=203528
  results:
  - test: text-decoration-thickness-linethrough-001.html
    status: FAIL
  - test: text-decoration-thickness-overline-001.html
    status: FAIL
  - test: text-decoration-thickness-scroll-001.html
    status: FAIL
  - test: text-decoration-thickness-underline-001.html
    status: FAIL
  - test: text-decoration-thickness-vertical-001.html
    status: FAIL
  - test: text-decoration-thickness-vertical-002.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=203529
  results:
  - test: text-decoration-underline-position-vertical-ja.html
    status: FAIL
  - test: text-decoration-underline-position-vertical.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=203530
  results:
  - test: text-decoration-line-recalc.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=203531
  results:
  - test: text-decoration-propagation-shadow.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=203528
  results:
  - test: text-decoration-thickness-linethrough-001.html
    status: FAIL
  - test: text-decoration-thickness-overline-001.html
    status: FAIL
  - test: text-decoration-thickness-scroll-001.html
    status: FAIL
  - test: text-decoration-thickness-underline-001.html
    status: FAIL
  - test: text-decoration-thickness-vertical-001.html
    status: FAIL
  - test: text-decoration-thickness-vertical-002.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=203529
  results:
  - test: text-decoration-underline-position-vertical-ja.html
    status: FAIL
  - test: text-decoration-underline-position-vertical.html
    status: FAIL
