links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=183258
  results:
  - test: line-breaking-002.html
    status: FAIL
  - test: line-breaking-004.html
    status: FAIL
  - test: line-breaking-006.html
    status: FAIL
  - test: line-breaking-007.html
    status: FAIL
  - test: line-breaking-009.html
    status: FAIL
  - test: line-breaking-011.html
    status: FAIL
  - test: line-breaking-ic-002.html
    status: FAIL
  - test: line-breaking-ic-003.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=183258
  results:
  - test: line-breaking-002.html
    status: FAIL
  - test: line-breaking-004.html
    status: FAIL
  - test: line-breaking-006.html
    status: FAIL
  - test: line-breaking-007.html
    status: FAIL
  - test: line-breaking-009.html
    status: FAIL
  - test: line-breaking-011.html
    status: FAIL
  - test: line-breaking-ic-002.html
    status: FAIL
  - test: line-breaking-ic-003.html
    status: FAIL
