links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=157477
  results:
  - test: display-contents-dynamic-table-001-inline.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=203606
  results:
  - test: display-change-object-iframe.html
    status: FAIL
  - test: display-contents-shadow-dom-1.html
    status: CRASH
  - test: display-flow-root-list-item-001.html
    status: FAIL
  - test: select-4-option-optgroup-display-none.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=157477
  results:
  - test: display-contents-dynamic-table-001-inline.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=203606
  results:
  - test: display-change-object-iframe.html
    status: FAIL
  - test: display-contents-shadow-dom-1.html
    status: TIMEOUT
  - test: display-flow-root-list-item-001.html
    status: FAIL
  - test: select-4-option-optgroup-display-none.html
    status: FAIL
