links:
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=204115
  results:
  - test: pointerevent_change-touch-action-onpointerdown_touch.html
    status: ERROR
  - test: pointerevent_pointercancel_touch.html
    status: ERROR
  - test: pointerevent_pointerleave_after_pointercancel_touch.html
    status: ERROR
  - test: pointerevent_pointerout_after_pointercancel_touch.html
    status: ERROR
  - test: pointerevent_pointerout_pen.html
    status: ERROR
  - test: pointerevent_releasepointercapture_onpointercancel_touch.html
    status: ERROR
  - test: pointerevent_touch-action-auto-css_touch.html
    status: ERROR
  - test: pointerevent_touch-action-inherit_highest-parent-none_touch.html
    status: ERROR
  - test: pointerevent_touch-action-pan-x-pan-y_touch.html
    status: ERROR
