links:
- product: firefox
  results:
  - subtest: Test that inset-inline shorthand sets longhands and serializes correctly.
    test: logical-box-inset.html
  - subtest: Test that inset shorthand sets longhands and serializes correctly.
    test: logical-box-inset.html
  - subtest: Test that inset-block shorthand sets longhands and serializes correctly.
    test: logical-box-inset.html
  - subtest: Test that margin-inline shorthand sets longhands and serializes correctly.
    test: logical-box-margin.html
  - subtest: Test that margin shorthand sets longhands and serializes correctly.
    test: logical-box-margin.html
  - subtest: Test that margin-block shorthand sets longhands and serializes correctly.
    test: logical-box-margin.html
  - subtest: Test that padding-block shorthand sets longhands and serializes correctly.
    test: logical-box-padding.html
  - subtest: Test that padding-inline shorthand sets longhands and serializes correctly.
    test: logical-box-padding.html
  - subtest: Test that padding shorthand sets longhands and serializes correctly.
    test: logical-box-padding.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=137688
- product: firefox
  results:
  - subtest: Logical shorthands follow the usual prioritization based on number of
      component longhands
    test: animation-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1289155
- product: firefox
  results:
  - subtest: Physical shorthands win over logical shorthands
    test: animation-001.html
  - subtest: Physical shorthands using variables win over logical shorthands
    test: animation-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1520069
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=190032
  results:
  - test: animation-003.tentative.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=190032
  results:
  - test: animation-003.tentative.html
    status: FAIL
