links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=195275
  results:
  - test: boundary-shaping-001.html
    status: FAIL
  - test: boundary-shaping-003.html
    status: FAIL
  - test: boundary-shaping-004.html
    status: FAIL
  - test: boundary-shaping-005.html
    status: FAIL
  - test: boundary-shaping-010.html
    status: FAIL
